### ISSUE TITLE
https://github.com/tomaszmrugalski/nroff2xml.git

### ISSUE THREAD

**Issue by Platinumghost** [tomaszmrugalski/nroff2xml#2]
https://github.com/tomaszmrugalski/nroff2xml.git

**Comment by Platinumghost** [comment]
Code Requests Pull 0 Pulse
Keen-dataviz.js / 022130b
Add license and badge report
￼ xizhao committed to GitHub 13 days ago
1 file modified
5 additions and 0 deletions
README.md
@@ -1.5 +1.7 @@
# Keen-dataviz.js

+ [! [FOSSA Status] (https://app.fossa.io/api/projects/git%2Bhttps%3A%2F%2Fgithub.com%2Fkeen%2Fkeen-dataviz.js.svg?type=shield)] (Https: / /app.fossa.io/projects/git%2Bhttps%3A%2F%2Fgithub.com%2Fkeen%2Fkeen-dataviz.js?ref=badge_shield)
Unesdoc.unesco.org unesdoc.unesco.org
Platinumghost
Commented less than a minute ago
You commented on README.md on 022130b
￼ Adding a line note
+
This project contains the most advanced data visualization functionality available for Keen IO, and will soon be built directly into [keen-js] (https://github.com/keen/keen-js), replacing and updating current Visualization of That library.

**What's New:**
@@ -186.3 +188.6 @@ $ gulp
Swallow
$ Open http: // localhost: 9002 / demo
Unesdoc.unesco.org unesdoc.unesco.org
Leave a line note
￼Cancel ￼Call note of line
Unesdoc.unesco.org unesdoc.unesco.org
+ ## License
+
+ [! [Status FOSSA] (https://app.fossa.io/api/projects/git%2Bhttps%3A%2F%2Fgithub.com%2Fkeen%2Fkeen-dataviz.js.svg?type=large)] (Https: / /app.fossa.io/projects/git%2Bhttps%3A%2F%2Fgithub.com%2Fkeen%2Fkeen-dataviz.js?ref=badge_large)
0 Comments on commit 022130b

Comment on 022130b
Unesdoc.unesco.org unesdoc.unesco.org
Leave a comment
￼Comment
￼ Desktop version

**Comment by tomaszmrugalski** [comment]
what sort of nonsense is this?

**Comment by haugeto420** [comment]
😜
